nome= str(input('Digíte seu nome completo: ')).strip()
print('Analisando seu nome')
print('Seu nomme em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primerio nome tem {} letras'.format(nome.find(' ')))
separa= nome.split()
print('Seu primeiro nome {} tem {} letras'.format(separa[0], len(separa[0])))